kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discovery-client
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "pods", "configmaps", "endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-service-sa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: client-service-rb
subjects:
  - kind: ServiceAccount
    name: client-service-sa
roleRef:
  kind: ClusterRole
  name: service-discovery-client
  apiGroup: rbac.authorization.k8s.io